"$pattern" : "replacement" | "assertion"

"$pattern2" : "replacement" | ""

"$pattern": "replacement" |"assertion"

"$pattern":
"replacement"|
"assertion"

"$pattern"
    : "replacement"
    | "assertion"

"$pattern3":
	"replacement"	|	"assertion"

"$pattern4"
:
"replacement"
|
"assertion"

all of the above are valid.
everything that is not, will be ignored. (basically everything from now on)
NOTE: the '$' before the pattern makes sure, that noone unknowingly replaces all occurences of "pattern" in your commandblocks
    (by just typing /cc <radius> without setting up the config and specifying rules in chat)
	(i just assumed "$pattern" is unlikely to be found in a commandblock)

# you may or may not use yaml comments, whichever you prefer
# duplicate patterns will be removed (so the first one is the one that counts).
# so effectively this config contains 4 entries: $pattern, $pattern2, $pattern3, $pattern4.

Here is a real Example:

# ";?([\\[, ]{1});>(g|gamemode)<;;?(?: *)=;?(?: *);>(0|s|survival)|(1|c|creative)|(2|a|adventure)|(3|sp|spectator)<;;?([\\], ]{1})":
#	";:(1);:(2)=;:(3);:(4)"
#|	""

it replaces every g=1 or g=s or gamemode=3 or g=spectator through the now in 1.13 valid syntax gamemode=fulldescription


invalid is for example:

pattern : replacement | assertion
#--> missing quotes

"pattern" : "replacement"
#--> no assertion

"pattern" | "assertion"
#--> no replacement

"pattern" | "assertion" : "replacement"
#--> wrong order

# "pattern" : "replacement" | "assertion"
#--> it's commented

hello there "pattern" : "replacement" | "assertion"
#--> has to start with arrangement of whitespaces followed by a quotation mark
    #--> valid is any combination of ' ' and '\t' before the entry
    
"pattern":

	"replacement" | "assertion"
#--> too many line breaks. to prevent unwanted entrys from syntax errors of previous lines
	#--> for maximum line spacing see $pattern4.
    
    
    
    
NOTE: if you really want the exact syntax requirement for these entrys, have the regex pattern it's matched with:
#--> (?:^|\n)[ \t]*\"(.+)\"[ \t]*\n?[ \t]*:[ \t]*\n?[ \t]*\"(.*)\"[ \t]*\n?\[ \t]*|[ \t]*\n?[ \t]*\"(.*)\"