";?([a-zA-Z]+) is working at ;?([a-zA-Z]+)! (Test)": ";!(2) is love, ;!(2) is life, ;!(1)"
"/summon ;?([^ ]+) ;?(.*) ;?(\\{.+\\})": "/summon ;!(1);!(3) ;!(2)"
"score_;?(.+)_min=;?([-\\d]+);?(.*);?(, +)score_;?(\\1)=;?([-\\d]+)": "scores=[;!(1)=;!(2)..;!(6)];!(3)"